<?php
$title = 'ajouter nouvelle note';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('etunote', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('etu'));
 echo $this->formRow($form->get('cours'));
 echo $this->formRow($form->get('exercice'));
 echo $this->formrow($form->get('note'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 
 ?>