


<?php
// module/Album/view/album/album/index.phtml:

$title = 'Les notes';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p><a href="<?php echo $this->url('etunote', array(
        'action'=>'add'));?>">ajouter nouvelle note</a></p>

<table class="table">
<tr>
    <th>Etu</th>
    <th>Exercice</th>
    <th>Cours</th>
    <th>Note</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($etunotes as $etunote) : ?>
<tr>
    <td><?php echo $this->escapeHtml($etunote->etu);?></td>
    <td><?php echo $this->escapeHtml($etunote->exercice);?></td>
    <td><?php echo $this->escapeHtml($etunote->cours);?></td>
    <td><?php echo $this->escapeHtml($etunote->note);?> </td>    
    <td>
        <a href="<?php echo $this->url('etunote',
            array('action'=>'edit', 'id' => $etunote->id));?>">Edit</a>
        <a href="<?php echo $this->url('etunote',
             array('action'=>'delete', 'id' => $etunote->id));?>">Delete</a>
            
           
    </td>
</tr>
<?php endforeach; ?>
</table>


